# Generated by Django 5.2.1 on 2026-08-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_finalgradesheet_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsubmission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/images/'),
        ),
    ]
