# Generated by Django 5.2.1 on 2026-08-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_assessmentsubmission_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='finalgradesheet',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
