# Generated by Django 5.2.1 on 2026-08-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_assessmentsubmission_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['school_class', 'created_at'], name='school_asse_school__c15d21_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['teacher', 'created_at'], name='school_asse_teacher_7b1541_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsubmission',
            index=models.Index(fields=['assessment', 'status'], name='school_asse_assessm_14561d_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsubmission',
            index=models.Index(fields=['student', 'status'], name='school_asse_student_f2b348_idx'),
        ),
        migrations.AddIndex(
            model_name='finalgradesheet',
            index=models.Index(fields=['school_class', 'published'], name='school_fina_school__e94341_idx'),
        ),
        migrations.AddIndex(
            model_name='finalgradesheet',
            index=models.Index(fields=['student', 'term'], name='school_fina_student_3e0142_idx'),
        ),
    ]
