# Generated by Django 5.2.1 on 2026-08-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_assessment_school_asse_school__c15d21_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assessments/'),
        ),
    ]
